### ISSUE TITLE
Need to change webpack config to make it work

### ISSUE THREAD

**Issue by abeauvois** [Chion82/rnweb-native-base-starter#1]
After following the complete setup process, I faced a blank page and several errors in the console like : 'Can't resolve module react-dom/lib/EventConstants'.

This remembers me another similar lib issue where it was the React version that moved react libs to react-dom libs.

By making aliases in webpack.config.dev.js it works well. Hope it helps others.

```
  resolve: {
    alias: {
      'react-native': 'react-native-web-extended',
      'native-base': 'native-base-web',
      'react/lib/EventConstants': 'react-dom/lib/EventConstants',
      'react/lib/EventPluginRegistry': 'react-dom/lib/EventPluginRegistry',
      'react/lib/ResponderEventPlugin': 'react-dom/lib/ResponderEventPlugin',
      'react/lib/ResponderTouchHistoryStore': 'react-dom/lib/ResponderTouchHistoryStore',
      'react/lib/TouchHistoryMath': 'react-dom/lib/TouchHistoryMath',
      'react/lib/CSSPropertyOperations': 'react-dom/lib/CSSPropertyOperations',
      'react/lib/ReactNativePropRegistry': 'react-native-web-extended/dist/modules/ReactNativePropRegistry',
      //Icon.TabBarItem
      'react-native-vector-icons/Ionicons': 'native-base-web/dist/Components/Widgets/Icon'
    }
  }
```

**Comment by Chion82** [comment]
Actually it's not just about a webpack resolve problem. Upgrading react and react-dom results in breaking the whole react-native-web. Currently I locked them to version 15.3.1 for temporary workaround.

**Comment by Chion82** [comment]
By merging `react-native-web-extended` with the latest upstream branch, this problem is resolved. Dependencies have been updated.
